Repository kzi-nastava/ma-project-event-planner-siit-2024-team-11, pull requests merged in 2025-02, with the labels that each got.

#32 Feature/solution details
  Eventy/app/src/main/java/com/example/eventy/MainActivity.java
  Eventy/app/src/main/java/com/example/eventy/adapters/solutions/FeaturedSolutionsAdapter.java
  Eventy/app/src/main/java/com/example/eventy/adapters/solutions/SolutionsAdapter.java
  Eventy/app/src/main/java/com/example/eventy/solutions/SolutionDetailsFragment.java
  Eventy/app/src/main/java/com/example/eventy/solutions/model/SolutionCard.java
  Eventy/app/src/main/java/com/example/eventy/solutions/services/SolutionService.java
  Eventy/app/src/main/java/com/example/eventy/users/profile/OtherUserProfilePageFragment.java
  Eventy/app/src/main/res/layout/fragment_home_featured_product_card.xml
  Eventy/app/src/main/res/layout/fragment_home_featured_service_card.xml
  Eventy/app/src/main/res/layout/fragment_product_card.xml
  Eventy/app/src/main/res/layout/fragment_service_card.xml
  Eventy/app/src/main/res/layout/fragment_solution_details.xml
  Eventy/app/src/main/res/navigation/mobile_navigation.xml
Labels: enhancement

#33 Feature/event stats
  Eventy/app/build.gradle.kts
  Eventy/app/src/main/java/com/example/eventy/MainActivity.java
  Eventy/app/src/main/java/com/example/eventy/events/eventstats/EventStatsAdapter.java
  Eventy/app/src/main/java/com/example/eventy/events/eventstats/EventStatsCardFragment.java
  Eventy/app/src/main/java/com/example/eventy/events/eventstats/EventsStatsFragment.java
  Eventy/app/src/main/java/com/example/eventy/events/model/EventStats.java
  Eventy/app/src/main/java/com/example/eventy/events/services/EventService.java
  Eventy/app/src/main/java/com/example/eventy/users/services/LoggedInHelperService.java
  Eventy/app/src/main/res/drawable/icon_bar_chart.xml
  Eventy/app/src/main/res/layout/fragment_event_stats_card.xml
  Eventy/app/src/main/res/layout/fragment_events_stats.xml
  Eventy/app/src/main/res/menu/activity_main_drawer.xml
  Eventy/app/src/main/res/navigation/mobile_navigation.xml
Labels: enhancement

#34 Improvement/services
  Eventy/app/src/main/java/com/example/eventy/MainActivity.java
  Eventy/app/src/main/java/com/example/eventy/adapters/solutions/SolutionsAdapter.java
  Eventy/app/src/main/java/com/example/eventy/services/ReservationSelectEventFragment.java
  Eventy/app/src/main/java/com/example/eventy/services/ServiceCreationFragment.java
  Eventy/app/src/main/java/com/example/eventy/services/ServiceDurationFragment.java
  Eventy/app/src/main/java/com/example/eventy/services/ServiceEditingFragment.java
  Eventy/app/src/main/java/com/example/eventy/services/ServiceManipulationFragment.java
  Eventy/app/src/main/java/com/example/eventy/services/model/CreateService.java
  Eventy/app/src/main/java/com/example/eventy/services/model/UpdateService.java
  Eventy/app/src/main/java/com/example/eventy/services/services/ServiceService.java
  Eventy/app/src/main/java/com/example/eventy/solutions/SolutionDetailsFragment.java
  Eventy/app/src/main/java/com/example/eventy/solutions/model/SolutionDetails.java
  Eventy/app/src/main/java/com/example/eventy/solutions/services/SolutionService.java
  Eventy/app/src/main/java/com/example/eventy/users/profile/PUPOwnServicesFragment.java
  Eventy/app/src/main/java/com/example/eventy/users/services/UserService.java
  Eventy/app/src/main/res/layout/fragment_service_creation.xml
  Eventy/app/src/main/res/layout/fragment_service_duration.xml
  Eventy/app/src/main/res/layout/fragment_service_editing.xml
  Eventy/app/src/main/res/layout/fragment_service_manipulation.xml
  Eventy/app/src/main/res/layout/fragment_solution_details.xml
  Eventy/app/src/main/res/menu/activity_main_drawer.xml
  Eventy/app/src/main/res/navigation/mobile_navigation.xml
Labels: enhancement

#35 Notifications - FRONTEND & BACKEND
  Eventy/app/build.gradle.kts
  Eventy/app/src/main/AndroidManifest.xml
  Eventy/app/src/main/java/com/example/eventy/MainActivity.java
  Eventy/app/src/main/java/com/example/eventy/adapters/notifications/NotificationsAdapter.java
  Eventy/app/src/main/java/com/example/eventy/custom/CreateReviewDialog.java
  Eventy/app/src/main/java/com/example/eventy/events/SelectEventFragment.java
  Eventy/app/src/main/java/com/example/eventy/events/services/EventService.java
  Eventy/app/src/main/java/com/example/eventy/home/HomeFragment.java
  Eventy/app/src/main/java/com/example/eventy/interactions/model/Notification.java
  Eventy/app/src/main/java/com/example/eventy/interactions/model/NotificationType.java
  Eventy/app/src/main/java/com/example/eventy/interactions/notifications/NotificationsFragment.java
  Eventy/app/src/main/java/com/example/eventy/interactions/service/NotificationHelper.java
  Eventy/app/src/main/java/com/example/eventy/interactions/service/NotificationService.java
  Eventy/app/src/main/java/com/example/eventy/reviews/model/CreateReview.java
  Eventy/app/src/main/java/com/example/eventy/reviews/model/UnreviewedEvent.java
  Eventy/app/src/main/java/com/example/eventy/reviews/service/ReviewService.java
  Eventy/app/src/main/java/com/example/eventy/services/ReservationFragment.java
  Eventy/app/src/main/java/com/example/eventy/users/login/LoginFragment.java
  Eventy/app/src/main/java/com/example/eventy/users/model/UserNotificationInfo.java
  Eventy/app/src/main/java/com/example/eventy/users/services/UserService.java
  Eventy/app/src/main/java/com/example/eventy/users/view_model/UserNotificationInfoViewModel.java
  Eventy/app/src/main/java/com/example/eventy/utils/ClientUtils.java
  Eventy/app/src/main/java/com/example/eventy/utils/FragmentTransition.java
  Eventy/app/src/main/res/drawable/icon_circle_red.xml
  Eventy/app/src/main/res/drawable/icon_favorite_smaller_white.xml
  Eventy/app/src/main/res/drawable/icon_notifications_red_dot.xml
  Eventy/app/src/main/res/drawable/icon_star_gold.xml
  Eventy/app/src/main/res/drawable/icon_star_grey.xml
  Eventy/app/src/main/res/drawable/notification_type_blue_teal.xml
  Eventy/app/src/main/res/drawable/notification_type_brown.xml
  Eventy/app/src/main/res/drawable/notification_type_dark_orange_red.xml
  Eventy/app/src/main/res/drawable/notification_type_dark_yellow.xml
  Eventy/app/src/main/res/drawable/notification_type_eventy_blue.xml
  Eventy/app/src/main/res/drawable/notification_type_green.xml
  Eventy/app/src/main/res/drawable/notification_type_product_pink.xml
  Eventy/app/src/main/res/drawable/notification_type_red.xml
  Eventy/app/src/main/res/drawable/notification_type_service_yellow.xml
  Eventy/app/src/main/res/drawable/notifications_mute_all.xml
  Eventy/app/src/main/res/drawable/notifications_unmute_all.xml
  Eventy/app/src/main/res/layout/dialog_create_review.xml
  Eventy/app/src/main/res/layout/fragment_notification_card.xml
  Eventy/app/src/main/res/layout/fragment_notifications.xml
  Eventy/app/src/main/res/navigation/mobile_navigation.xml
  Eventy/app/src/main/res/values/page_size_options.xml
  Eventy/app/src/main/res/values/styles.xml
Labels: bug, enhancement

#36 Feature/product management
  Eventy/app/src/main/java/com/example/eventy/MainActivity.java
  Eventy/app/src/main/java/com/example/eventy/products/ProductCreationFragment.java
  Eventy/app/src/main/java/com/example/eventy/products/ProductUpdateFragment.java
  Eventy/app/src/main/java/com/example/eventy/products/model/CreateProduct.java
  Eventy/app/src/main/java/com/example/eventy/products/model/Product.java
  Eventy/app/src/main/java/com/example/eventy/products/services/ProductService.java
  Eventy/app/src/main/java/com/example/eventy/users/services/LoggedInHelperService.java
  Eventy/app/src/main/java/com/example/eventy/utils/ClientUtils.java
  Eventy/app/src/main/res/drawable/icon_add_product.xml
  Eventy/app/src/main/res/layout/fragment_product_creation.xml
  Eventy/app/src/main/res/layout/fragment_product_update.xml
  Eventy/app/src/main/res/menu/activity_main_drawer.xml
  Eventy/app/src/main/res/navigation/mobile_navigation.xml
Labels: enhancement

#37 Feature/purchase product
  Eventy/app/src/main/java/com/example/eventy/MainActivity.java
  Eventy/app/src/main/java/com/example/eventy/products/ProductPurchaseFragment.java
  Eventy/app/src/main/java/com/example/eventy/products/model/Purchase.java
  Eventy/app/src/main/java/com/example/eventy/products/services/ProductService.java
  Eventy/app/src/main/java/com/example/eventy/services/ServiceManipulationFragment.java
  Eventy/app/src/main/java/com/example/eventy/solutions/SolutionDetailsFragment.java
  Eventy/app/src/main/res/layout/fragment_product_purchase.xml
  Eventy/app/src/main/res/navigation/mobile_navigation.xml
Labels: enhancement

#38 Reviews (admin) - FRONTEND & BACKEND
  Eventy/app/src/main/java/com/example/eventy/MainActivity.java
  Eventy/app/src/main/java/com/example/eventy/adapters/reviews/PendingReviewsAdapter.java
  Eventy/app/src/main/java/com/example/eventy/custom/ReviewDetailsDialog.java
  Eventy/app/src/main/java/com/example/eventy/reviews/PendingReviewsFragment.java
  Eventy/app/src/main/java/com/example/eventy/reviews/model/Review.java
  Eventy/app/src/main/java/com/example/eventy/reviews/service/ReviewService.java
  Eventy/app/src/main/java/com/example/eventy/users/services/LoggedInHelperService.java
  Eventy/app/src/main/res/drawable/icon_accept.xml
  Eventy/app/src/main/res/drawable/icon_decline_review.xml
  Eventy/app/src/main/res/drawable/icon_pending_reviews.xml
  Eventy/app/src/main/res/drawable/review_accept_button_background.xml
  Eventy/app/src/main/res/drawable/review_comment_border.xml
  Eventy/app/src/main/res/drawable/review_decline_button_background.xml
  Eventy/app/src/main/res/layout/dialog_review_details.xml
  Eventy/app/src/main/res/layout/fragment_pending_review.xml
  Eventy/app/src/main/res/layout/fragment_pending_reviews.xml
  Eventy/app/src/main/res/menu/activity_main_drawer.xml
  Eventy/app/src/main/res/navigation/mobile_navigation.xml
  Eventy/app/src/main/res/values/page_size_options.xml
Labels: enhancement

#40 Blocks - FRONTEND & BACKEND
  Eventy/app/src/main/java/com/example/eventy/adapters/events/EventsAdapter.java
  Eventy/app/src/main/java/com/example/eventy/adapters/events/EventsSingleSelectionAdapter.java
  Eventy/app/src/main/java/com/example/eventy/adapters/events/FeaturedEventsAdapter.java
  Eventy/app/src/main/java/com/example/eventy/custom/BlockUserDialog.java
  Eventy/app/src/main/java/com/example/eventy/events/EventDetailsDialog.java
  Eventy/app/src/main/java/com/example/eventy/events/eventdetails/EventDetailsFragment.java
  Eventy/app/src/main/java/com/example/eventy/events/eventstats/EventStatsAdapter.java
  Eventy/app/src/main/java/com/example/eventy/events/model/EventCard.java
  Eventy/app/src/main/java/com/example/eventy/services/ReservationSelectEventFragment.java
  Eventy/app/src/main/java/com/example/eventy/solutions/SolutionDetailsFragment.java
  Eventy/app/src/main/java/com/example/eventy/users/model/BlockUser.java
  Eventy/app/src/main/java/com/example/eventy/users/profile/OtherUserProfilePageFragment.java
  Eventy/app/src/main/java/com/example/eventy/users/services/UserService.java
  Eventy/app/src/main/res/layout/dialog_block_user.xml
  Eventy/app/src/main/res/layout/fragment_other_user_profile_page.xml
  Eventy/app/src/main/res/menu/activity_main_drawer.xml
Labels: enhancement, improvement
